name: Build iOS App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          set -e

          # Packages we desperately need
          brew install ldid
          brew install dpkg

          # Run setup script to download dependencies (LLVM)
          chmod +x setup.sh
          ./setup.sh

      - name: Build Jailed
        run: |
          set -e

          # Build the project (jailed)
          make jailed

      - name: Build Rootless
        run: |
          set -e

          # Build the project (rootless)
          make rootless

      - name: Build Roothide
        run: |
          set -e

          # Build the project (roothide)
          make roothide

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            '*.ipa'
            '*.deb'

      - name: Cleanup
        run: |
          set -e

          # Cleanup artifacts
          make cleanup-artifacts
