name: Build iOS App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: macos-26
    continue-on-error: true
    strategy:
      matrix:
        include:
          - target: jailed
            name: nyxian.ipa
            
          - target: rootless
            name: nyxian_rootless.deb
            
          - target: roothide
            name: nyxian_roothide.deb
            
          - target: rootful
            name: nyxian_rootful.deb
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          set -e

          # Packages we desperately need
          brew install ldid dpkg libarchive

      - name: Cache Theos
        id: cache-theos
        uses: actions/cache@v4
        with:
          path: ~/theos
          key: theos-${{ runner.os }}-v1

      - name: Install Theos
        if: steps.cache-theos.outputs.cache-hit != 'true'
        run: |
          set -e

          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Setup
        run: |
          set -e

          # Setting TheOS stuff up
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "PATH=$HOME/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Build ${{ matrix.target }}
        timeout-minutes: 1200
        run: |
          set -e

          # Build the project
          make ${{ matrix.target }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: |
            nyxian.ipa
            nyxian*.deb
