name: Build iOS App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Nyxian Jailed
        run: |
          set -e

          # Run setup script to download dependencies
          chmod +x setup.sh
          ./setup.sh

          # Build the project (jailed)
          make jailed
          mv Nyxian.ipa Nyxian-Jailed.ipa
          make clean

      - name: Build Nyxian Jailbroken
        run: |
          set -e

          # Run setup script to download dependencies
          chmod +x setup.sh
          ./setup.sh

          # Build the project (jailed)
          make jailbroken
          mv Nyxian.ipa Nyxian-Jailbroken.ipa
          make clean


      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nyxian-Jailed.ipa
          path: Nyxian-Jailed.ipa

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nyxian-Jailbroken-Testing.ipa
          path: Nyxian-Jailbroken.ipa
