name: Build iOS App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          set -e

          # Packages we desperately need
          brew install ldid
          brew install dpkg

          # Run make command to download dependencies (LLVM)
          make LazySetup

      - name: Build Jailed
        run: |
          set -e

          # Build the project (jailed)
          make jailed

      - name: Build Rootless
        run: |
          set -e

          # Build the project (rootless)
          make rootless

      - name: Build Roothide
        run: |
          set -e

          # Build the project (roothide)
          make roothide

      - name: Upload Jailed
        uses: actions/upload-artifact@v4
        with:
          name: nyxian.ipa
          path: nyxian.ipa

      - name: Upload Rootless
        uses: actions/upload-artifact@v4
        with:
          name: nyxian_0.8.2_iphoneos-arm64.deb
          path: nyxian_0.8.2_iphoneos-arm64.deb

      - name: Upload Roothide
        uses: actions/upload-artifact@v4
        with:
          name: nyxian_0.8.2_iphoneos-arm64e.deb
          path: nyxian_0.8.2_iphoneos-arm64e.deb

